name: Docker Hub Description
on:
  push:
    branches:
    - main
jobs:
  sync-readme:
    runs-on: ubuntu-24.04
    if: ${{ github.repository == 'WeblateOrg/locale_lint' }}
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@0505d8b04853a30189aee66f5bb7fd1511bbac71 # v4.0.1
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        DOCKERHUB_REPOSITORY: weblate/locale_lint
permissions:
  contents: read
