name: Docker Hub Description
on:
  push:
    branches:
    - main
jobs:
  sync-readme:
    runs-on: ubuntu-24.04
    if: ${{ github.repository == 'WeblateOrg/locale_lint' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v4
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        DOCKERHUB_REPOSITORY: weblate/locale_lint
permissions:
  contents: read
