name: Docker Hub Description
on:
  push:
    branches:
    - main
jobs:
  sync-readme:
    runs-on: ubuntu-24.04
    if: ${{ github.repository == 'WeblateOrg/locale_lint' }}
    steps:
    - name: Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        persist-credentials: false
    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@432a30c9e07499fd01da9f8a49f0faf9e0ca5b77 # v4.0.2
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        DOCKERHUB_REPOSITORY: weblate/locale_lint
permissions:
  contents: read
