name: Distribution

on: [push, pull_request]

jobs:
  setup:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        persist-credentials: false
    - name: Setup Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: '3.13'
    - uses: astral-sh/setup-uv@d9e0f98d3fc6adb07d1e3d37f3043649ddad06a1 # v6.5.0
      with:
        enable-cache: true
        cache-dependency-glob: ''
    - name: Install dependencies
      run: uv pip install --system -e ".[test]"
    - name: build
      run: uv build
    - name: twine
      run: uvx twine check dist/*
    - name: Publish package
      if: ${{ github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags') }}
      run: uv publish --trusted-publishing always
permissions:
  contents: read
  id-token: write
