name: Distribution

on: [push, pull_request]

jobs:
  setup:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false
    - name: Setup Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: '3.13'
    - uses: astral-sh/setup-uv@c7f87aa956e4c323abf06d5dec078e358f6b4d04 # v6.0.0
      with:
        enable-cache: true
        cache-dependency-glob: ''
    - name: Install dependencies
      run: uv pip install --system -e ".[test]"
    - name: build
      run: uv build
    - name: twine
      run: uvx twine check dist/*
    - name: Publish package
      if: ${{ github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags') }}
      run: uv publish --trusted-publishing always
permissions:
  contents: read
  id-token: write
