name: Distribution

on: [push, pull_request]

jobs:
  setup:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: actions/cache@0c907a75c2c80ebcb7f088228285e798b750cf8f # v4.2.1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-setup-${{ hashFiles('**/requirements*.txt') }}
    - name: Setup Python
      uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install -r requirements-test.txt
    - name: build
      run: python -m build
    - name: twine
      run: twine check dist/*
    - name: Publish package
      if: ${{ github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags') }}
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
permissions:
  contents: read
