name: Distribution

on: [push, pull_request]

jobs:
  setup:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Setup Python
      uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0
      with:
        python-version: '3.13'
    - uses: astral-sh/setup-uv@22695119d769bdb6f7032ad67b9bca0ef8c4a174 # v5.4.0
      with:
        enable-cache: true
        cache-dependency-glob: ''
    - name: Install dependencies
      run: uv pip install --system -r requirements-test.txt
    - name: build
      run: uv build
    - name: twine
      run: uvx twine check dist/*
    - name: Publish package
      if: ${{ github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags') }}
      run: uv publish --trusted-publishing always
permissions:
  contents: read
